{{- if .Values.hpa -}}

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}-hpa
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
{{ include "app.annotation" . | indent 4 }}
spec:
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpu }}

{{- end }}