apiVersion: v1
appVersion: "0.1-snapshot"
description: "Springboot Helm Chart by" 
name: "dev-springboot"
version: "0.0.1-snaphot"
icon: https://spring.io/img/homepage/icon-spring-framework.svg
